apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lab-deployment
  labels:
    app: kube-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-lab
  template:
    metadata:
      labels:
        app: kube-lab
    spec:
      containers:
      - name: kube-lab-app
        image: kube-lab-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080