apiVersion: v1
kind: Service
metadata:
  name: kube-lab-service
  labels:
    app: kube-lab
spec:
  type: NodePort
  selector:
    app: kube-lab
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP